services:
  kotlin-r2dbc-common:
    image: postgres:17.5-alpine
    container_name: learning-webflux-kotlin-r2dbc-common
    env_file:
      - ../.env
    environment:
      - 'POSTGRES_DB=orders'
      - 'POSTGRES_USER=${PG_USER}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD}'
    ports:
      - '5432:5432'
