spring:
  application:
    name: slow-service

slow-service:
  delay-in-seconds: 0

server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
