spring:
  application:
    name: R2DBC Data Access Application (Common)
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/orders
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  sql:
    init:
      data-locations: classpath:schema.sql
      mode: always
